### ISSUE TITLE
The kernel appears to have died. It will restart automatically

### ISSUE THREAD

**Issue by robbine** [obryanlouis/qa#4]
I tried fusion net in a jupyter notebook.
However I came across this kernel died issue. Then I googled and found that it might be related to a pytorch bug. Is it possible to disable all cove ?

**Comment by obryanlouis** [comment]
Are you running the setup in jupyter? That is the only part that uses pytorch (to get the weights for cove). Otherwise, I would take a guess that it might be just running out of memory. You can disable cove during training/evaluation with the "--use_cove_vectors=False" option if you want, which will decrease the memory usage, although the thing that would probably help the most is to decrease the rnn size and batch size (you might try something small like "--rnn_size=10 --batch_size=2" just as a sanity check).

**Comment by robbine** [comment]
I tried to disable cove_vectors. After 5400 iters, the kernel died again. The output lines are listed below:

('[Validation] iteration:', '5400', 'loss: 3.782E+00')
('[Train] F1', 0.6678987623859639, 'Em', 0.5439243498817967)
('[Valid] F1', 0.6941714234415809, 'Em', 0.5908230842005676)
Time to evaluate train/val: 824.834594
Achieved new highest F1: 0.694171

​The last line indicates that a new f1 score is found and the model should be saved by "self.saver.save(self.session, self.checkpoint_file_name)"
However there isn't any checkpoint files in the checkpoint_dir.

**Comment by obryanlouis** [comment]
Perhaps jupyter itself is consuming more memory as time goes on due to the overhead? I'm not sure. Generally the program just dying like that means that memory ran out somewhere - although I can't say where in your case. I normally just run it from the command line.
I'm also not sure why the files wouldn't be saved in the checkpoint dir. I haven't seen that issue before. The saver's save method is implemented by Tensorflow itself. It could be a permissions issue. Please note that the "experiment_name" argument becomes part of the file names - so try to keep it simple like in ([a-z0-9]+).
I would recommend running the program outside of jupyter first if you haven't already. You can also try using "--use_fake_dataset=True" to do more debugging with a fake dataset and make sure things work OK before spending time on the real dataset.

**Comment by robbine** [comment]
I tried to save checkpoint every 100 steps. It works fine. 
so I believe it's a jupyter memory issue.
perhaps updating jsonschema could solve the problem
